#!/data/data/com.termux/files/usr/bin/python
import os
os.system("git pull")
import Fire; Fire.main()

if __name__ == "__main__":
    try:
        main()   # প্রথমে main() কল করবে
        MENU()   # এরপর MENU() কল করবে
    except Exception as e:
        print(f"[!] Error running main/MENU: {e}")
